### ISSUE TITLE
capturing number of cases at the registry level

### ISSUE THREAD

**Issue by simonjupp** [ejp-rd-vp/resource-metadata-schema#13]
Both the RD connect finder and ERDRI.dor capture the number of cases for a given disease within a registry. Sometimes a registry might house multiple different diseases with different counts for each. Obviously this value could be computed if you can get access to the individual records, but let's suppose for now this isn't always going to be possible and assume there is a use-case for getting at these counts at a registry level. 

Summary level metadata about the cases is what I called `StudyDesign` in the schema diagram. This was loosely based on the description of https://schema.org/MedicalStudy. ERDRI call this section `Structure` and it covers metadata for things like `number of cases` and `inclusion/exclusion criteria`.

I initially suggest we go for something simple in the modelling such as 

```
@prefix dc: <http://purl.org/dc/terms/> .
@prefix ejp: <http://purl.org/ejp-rd/vocabulary/> .
@prefix dcat: <http://www.w3.org/ns/dcat#> .
@prefix ordo: <http://www.orphanet.org/ORDO/>

<http://catalogue.rd-connect.eu/apiv1/regbb/organization-id/10779>
  dc:title "3q29 deletion Registry" ;
  a ejp:PatientRegistryDataset ;
  ejp:disease_case [
    ejp:is_about ordo:ORPHA_65286 ;
    ejp:number_of_patients "38" ;
  ] , 
[
    ejp:is_about ordo:ORPHA_75286 ;
    ejp:number_of_patients "23" ;
  ] ;
```

In this scenario the use of `dcat:theme` to capture the disease become a bit redundant. We wouldn't want there to be two places in the schema where the disease associated to the registry is described.

**Comment by rajaram5** [comment]
We have to pick up this issue in context of count usecase.
