### ISSUE TITLE
Metadata collection from catalogs

### ISSUE THREAD

**Issue by S2Ola** [ejp-rd-vp/resource-metadata-schema#19]
Actions: 

1. Collect the metadata in the EU-RD Platform 
2. Create a list of the metadata
3. Map the metdata to the Application ontology

**Comment by S2Ola** [comment]
Metadata of registry: 

- General information:
         -  Acronym 	
         -  Medical area 	
         - Type of Registry 	
         - Other type
         - Description 	
         - Registry is member of Eurocat? 	 
         - Website 
         - Sponsors 	

- Rare diseases
         - Name of the disease 
         - Registry information
         - Institution 	
         - Facility 	
         - Department 	
         - Street & number 	
         - Postcode City 	
         - Country 

- Responsible for the registry
         - Contact person 	
         - Position 	
         - E-Mail address 	
         - Phone number 

- Biobanks  
         -  Biobank name 	
         - Registry of biobanks 	
         -  Biobank identifier

- Additional components
         - Name of the component 	
         - Component described in 	Relationship component-registry

**Comment by S2Ola** [comment]
List of ERN Registries: 
Network Name | Description
1. ERN BOND | European Reference Network on bone disorders
2. ERN CRANIO | European Reference Network on craniofacial anomalies and ear, nose and throat (ENT) disorders
3. Endo-ERN | European Reference Network on endocrine conditionsm
4. ERN EpiCARE | European Reference Network on epilepsies
5. ERKNet | European Reference Network on kidney diseases
6. ERN-RND | European Reference Network on neurological diseases
7. ERNICA | European Reference Network on inherited and congenital anomalies
8. ERN LUNG | European Reference Network on respiratory diseases
9. ERN Skin | European Reference Network on skin disorders
10. ERN EURACAN | European Reference Network on adult cancers (solid tumours)
11. ERN EuroBloodNet | European Reference Network on haematological diseases
12. ERN eUROGEN | European Reference Network on urogenital diseases and conditions
13. ERN EURO-NMD | European Reference Network on neuromuscular diseases
14. ERN EYE | European Reference Network on eye diseases
15. ERN GENTURIS | European Reference Network on genetic tumour risk syndromes
16. ERN GUARD-HEART | European Reference Network on diseases of the heart
17. ERN ITHACA | European Reference Network on congenital malformations and rare intellectual disability
18. MetabERN | European Reference Network on hereditary metabolic disorders
19. ERN PaedCan | European Reference Network on paediatric cancer (haemato-oncology)
20. ERN RARE-LIVER | European Reference Network on hepatological diseases
21. ERN ReCONNET | European Reference Network on connective tissue and musculoskeletal diseases
22. ERN RITA | European Reference Network on immunodeficiency, autoinflammatory and autoimmune diseases
23. ERN TRANSPLANT-CHILD | European Reference Network on Transplantation in Children
24. VASCERN | European Reference Network on Rare Multisystemic Vascular Diseases

**Comment by rajaram5** [comment]
Not a relevant issue for this repository
