### ISSUE TITLE
Align current model with DCAT2

### ISSUE THREAD

**Issue by rajaram5** [ejp-rd-vp/resource-metadata-schema#23]
Align current version semantic model with Data Catalog Vocabulary (DCAT) - Version 2 https://www.w3.org/TR/vocab-dcat/

**Comment by matentzn** [comment]
@rajaram5 can you add me as owner to this repo?

**Comment by rajaram5** [comment]
I will ask Marc to add you to the list

**Comment by rajaram5** [comment]
This is done in release 1.0
