### ISSUE TITLE
Error in ejp-rd prefix in image

### ISSUE THREAD

**Issue by ronaldcornet** [ejp-rd-vp/resource-metadata-schema#31]
Image on main page of the Resource Semantic Metadata Schema has a typo in the ejp-rd prefix, now ending with "cvocabulary" instead of "vocabulary".

Looks great otherwise!
Any chance that some of the open issues can be closed now? 😀

**Comment by rajaram5** [comment]
Nice catch @ronaldcornet. @S2Ola can you fix this typo in the picture? 

![ejp-model](https://user-images.githubusercontent.com/4365683/112615262-8f59ee80-8e22-11eb-8e23-47bf9c834474.png)

**Comment by henrietteharmse** [comment]
No longer applicable
