### ISSUE TITLE
The definition and use of Location is confusing

### ISSUE THREAD

**Issue by henrietteharmse** [ejp-rd-vp/resource-metadata-schema#33]
My aim here is to start a discussion on this. It may be purely that I do not understand the intent here well enough.

I find the definition and use of Location shapes confusing in the metadata schema. There seems to be several approaches for defining location schema in different shape files. Here are the different approaches I noted:

1. ejp:location: location.shex, dataset.shex, dataservice.shex, catalog.shex

2. dc:Location: Used in biobank.shex, resource.shex, patientRegistry.shex, catalog.shex
```
:locationShape IRI {
  a [dct:Location];
  dct:title xsd:string;
  dct:description xsd:string*;
}
```

3. dc:spatial: Used in organization.shex.

It may be perfectly valid to have these different options for representing a location. However, it may be better to define the different options in single .shex file and import it into other .shex files where this is needed? The advantage is that if we need to change how we deal with locations, it can be done in a single place.

@rajaram5 Do you have any thoughts on this?

**Comment by rajaram5** [comment]
Good find @henrietteharmse. In the first version of the metadata model we decide to use this option (dc:Location: Used in biobank.shex, resource.shex, patientRegistry.shex, catalog.shex). But I see that later Ola added additional resources in which he did not use the agreed location model. I also see that he has overwritten the `location.shex` file of version 1 ;-). I propose that we use the model below for location. What do you think?

```
PREFIX : <http://purl.org/ejp-rd/metadata-model/v1/shex/>
PREFIX dct:   <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

:locationShape IRI {
  a [dct:Location];
  dct:title xsd:string;
  dct:description xsd:string*;
}

```

**Comment by henrietteharmse** [comment]
No longer applicable.
