### ISSUE TITLE
logoURL and homepage

### ISSUE THREAD

**Issue by markwilkinson** [ejp-rd-vp/resource-metadata-schema#41]
Because of https://github.com/ejp-rd-vp/resource-metadata-schema/issues/40#issuecomment-1562915427   we now have various levels of a DCAT record being independently discoverable.  Because of this, we need to hang the logoURL and homepage properties off of dcat:Resource, so that they propogate down to the catalog, dataset, distribution, and/or data service.

Thanks!

**Comment by henrietteharmse** [comment]
Thanks Mark, I will be able to attend to this around end of June.

**Comment by markwilkinson** [comment]
By the way, I did a sitewide search for "logo", and the logoURL property isn't documented anywhere, as far as I can tell...

**Comment by henrietteharmse** [comment]
Yes! There has been no logo in the metadata model as up to now, nor in DCAT2 as far as can tell. 
There is a `foaf:page` on `Organisation`, which I think should in fact be `foaf:homepage`. 

Questions:
1. Should `foaf:homepage` be removed from `Organisation`?
2. Adding `foaf:logo` and `foaf:homepage` to `dcat:Resouce` will also cause it to propagate to `ejprd:Biobank`, `ejprd:PatientRegistry` and `ejprd:Guideline`. Is that what you want?
3. Are `foaf:logo` and `foaf:homepage` optional? 
4. What cardinality apply to `foaf:logo` and `foaf:homepage`?

**Comment by markwilkinson** [comment]
1:  I don't think so, but Organization needs to be re-thought in any case... but not for the June release
2: yes
3: foaf:logo is optional.  homepage is no longer necessary since dcat:Resource has "landingPage"
4: I guess 1:1 for logo, and then we follow DCAT2 for landingPage (which appears to be 1:many)

**Comment by henrietteharmse** [comment]
Revise (4) 0..*

**Comment by henrietteharmse** [comment]
Add foaf:logo 0..1 to Organisation

**Comment by henrietteharmse** [comment]
```
3: foaf:logo is optional. homepage is no longer necessary since dcat:Resource has "landingPage"
4: I guess 1:1 for logo, and then we follow DCAT2 for landingPage (which appears to be 1:many)
```
@markwilkinson  0..1 for logo on Resource probably makes sense rather than 1..1?
