### ISSUE TITLE
Decision about logo

### ISSUE THREAD

**Issue by markwilkinson** [ejp-rd-vp/resource-metadata-schema#44]
logo should be associated with a dcat:Resource (not an agent)

logo should be optional

dcat:Resource already has a landingPage, so no additional web page element is necessary.

Decision will be ratified at P2 meeting on Friday

**Comment by henrietteharmse** [comment]
@markwilkinson  was this ratified?

**Comment by markwilkinson** [comment]
We ran out of time, but it doesn't make sense any other way, so... In the absence of any guidance, I think we need to do the most sensible thing.  We can discuss it in a half hour.
