### ISSUE TITLE
Decision on VPQueryable

### ISSUE THREAD

**Issue by markwilkinson** [ejp-rd-vp/resource-metadata-schema#45]
A long discussion resulted in a decision to change the ontology term from ejprd:VPQueryable --> ejprd:VPContentDiscovery

Decision will be ratified at P2 meeting on Friday

**Comment by markwilkinson** [comment]
so overall:

<resourceURI>  ejprd:vpConnection ejprd:VPDiscoverable
<resourceURI>  ejprd:vpConnection ejprd:VPContentDiscovery

**Comment by vabishaa** [comment]
Is there a deadline when this will be decided so that we can change it in the VP portal?

**Comment by henrietteharmse** [comment]
@vabishaa My understanding is that this has been decided. @markwilkinson Is this correct?

**Comment by markwilkinson** [comment]
It has been decided; however, not all FDPs have updated.  I don't know when that will happen... hopefully soon!

**Comment by henrietteharmse** [comment]
@markwilkinson  Should this not be `ejprd:VPContentDiscover**able**` rather than  `ejprd:VPContentDiscover**y**` to be aligned with `ejprd:VPDiscoverable`?

**Comment by henrietteharmse** [comment]
@markwilkinson I assume `ejprd:VPContentDiscoverable` implies `ejprd:VPDiscoverable`?

**Comment by markwilkinson** [comment]
ContentDiscovery is what was decided, and what the FDPs are now configured to provide... so please use that :-)

**Comment by markwilkinson** [comment]
VPDiscoverable indicates that you are requesting to be indexed by the platform

VPContentDiscovery indicates that you have implemented the /individuals interface for Beacon2

This should be added to the documentation, please.
