### ISSUE TITLE
endpointURL in Data Service

### ISSUE THREAD

**Issue by markwilkinson** [ejp-rd-vp/resource-metadata-schema#48]
endpointURL  should be [0..1]

There are two different kinds of services.  Some services provide a website as their interface, while others are more "Swaggery".  
For the first type, we require a dcat:landingPage
For the second type, we require a dcat:endpoingURL, and a dcat:serviceDescription (pointing to theYAMLy kind of interface definition)

**Comment by henrietteharmse** [comment]
See commits [this](https://github.com/ejp-rd-vp/resource-metadata-schema/commit/7b81b676ae32c4efb3068a47911d377005917154) and [that](https://github.com/ejp-rd-vp/resource-metadata-schema/commit/2478c1dc227a550f451838b65723e2f9aa2e0ac7).
