### ISSUE TITLE
Metdata model diagram is missing accessService property on Distribution

### ISSUE THREAD

**Issue by markwilkinson** [ejp-rd-vp/resource-metadata-schema#52]
In the FDP reference implementation, the only way to create a Data Service ("type 2") is to create it as a connection from dcat:Distribution.  

The property connecting a distribution to a data service is:
dcat:accessService

In the diagram (and in the reference implementation) there is a property of Data Service "dcat:servesDataset" which points to the Dataset, but in practice that field is EXTREMELY difficult to fill correctly!  So the missing property described above is the more important one, and the one that is required by the FDP.

**Comment by henrietteharmse** [comment]
Using the Excel template `dcat:accessService` can be filled by selecting datasets that have already been added to the template.
