### ISSUE TITLE
Dataset has no pointer to Distribution

### ISSUE THREAD

**Issue by nirupamaBenis** [ejp-rd-vp/resource-metadata-schema#54]
In this page  https://github.com/ejp-rd-vp/resource-metadata-schema/blob/master/template/Dataset.md you can mention which registry or biobank the dataset is related to but not the distribution that it might have. (Onboarding Team)

**Comment by henrietteharmse** [comment]
The link from a Dataset to a Distribution is made when you create the Distribution because a distribution cannot exist without a Dataset. This is the "DatasetTitle" on the Distribution tab in the template.
