### ISSUE TITLE
Some inconsistencies in the use of LandingPage and foaf:page

### ISSUE THREAD

**Issue by nirupamaBenis** [ejp-rd-vp/resource-metadata-schema#55]
Was there a decision made on using one of the two consistently?

**Comment by henrietteharmse** [comment]
As discussed in the meeting on Wed `foaf:page` is replaced with `foaf:homepage` as that makes more sense - a page can really be anything where homepage is what is intended.  `foaf:homepage` is used on Organization, LandingPage is used for Resources, Datasets, DataServices, Catalogs, Biobanks, PatientRegistries and Guidelines.
