### ISSUE TITLE
Remove VPContentDiscovery Tag (Replace with Instructions on Describing Service)

### ISSUE THREAD

**Issue by HaddadTala** [ejp-rd-vp/resource-metadata-schema#59]
Mark W to provide description of how resources can specify their endpoint. Once done the ContentDiscovery TAg an be eliminated. Rresources and tech teams to be notified.

**Comment by markwilkinson** [comment]
See issue provided here:  https://github.com/ejp-rd-vp/resource-metadata-schema-ontology/issues/1

**Comment by henrietteharmse** [comment]
@HaddadTala @markwilkinson Can either of you provide descriptions for VPBeacon2_individuals and VPBeacon2_catalog?

**Comment by henrietteharmse** [comment]
@HaddadTala @markwilkinson Please, can either of you provide descriptions for VPBeacon2_individuals and VPBeacon2_catalog?

**Comment by henrietteharmse** [comment]
Pressed wrong button by accident!

**Comment by markwilkinson** [comment]
VPBeacon2_individuals:  the annotated resource (always a DataService) provides the Beacon2 /individuals interface

VPBeacon2_catalog:   the annotated resource (always a DataService) provides the Beacon2 /catalog interface

**Comment by markwilkinson** [comment]
These are values of "dcat:theme".  Any DataService functional annotation can appear as a value for dcat:theme, using EDAM as a common source of annotations.
