### ISSUE TITLE
Ontology link not working

### ISSUE THREAD

**Issue by nirupamaBenis** [ejp-rd-vp/resource-metadata-schema#61]
http://purl.org/ejp-rd/vocabulary/VPDiscoverable
This link is in the Onboarding document which will be widely circulated, if we are using the wrong link please do let us know.

**Comment by henrietteharmse** [comment]
Hi Niru, 

As you will see [here](https://github.com/ejp-rd-vp/resource-metadata-schema-ontology/blob/9c8ce7e7ee035fec86445fafc979d083634487f4/ejprd_resource_metadata_ontology.owl#L4193) it has not changed.

You need to take this up with whomever is maintaining this link.
