### ISSUE TITLE
Onboarding document review 

### ISSUE THREAD

**Issue by HaddadTala** [ejp-rd-vp/resource-metadata-schema#63]
Upon the review of the onboarding document, the team has a few items that require confirmation (https://ejprd.sharepoint.com/:w:/r/sites/pillar2-central9/Shared%20Documents/General/3.3_WF_FAIRification/OnboardingTasks/Onboarding%20document%202.0.docx?d=wf386b4e9247b47b3bdc049bb9cff57e5&csf=1&web=1&e=aSim66):

Can you kindly take a look at the questions under the following sections:
1. DataService properties 

- dataset title - pg 29 (can you confirm dct:title is the correct property to use) question for @henrietteharmse 
- accessService property - pg 29 (should we remove it?) question for @markwilkinson @henrietteharmse 

2. Guideline no properties found pg 30 (should we remove it from the documentation altogether?) question for @henrietteharmse

**Comment by markwilkinson** [comment]
accessService property is incorrect in the metadata schema.  It is a property of a Dataset, not a property of a DataService.

In the onboarding documentation, it is probably best to remove it...

**Comment by henrietteharmse** [comment]
>     DataService properties
> 
>     dataset title - pg 29 (can you confirm dct:title is the correct property to use) question for @henrietteharmse
Yes, that is a `dct:title`.

> accessService property - pg 29 (should we remove it?) question for @markwilkinson @henrietteharmse
Yes, you should remove it. It is a property of `dcat:Distribution` in DCAT with type `dcat:DataService`.

> Guideline  extends `dcat:Resource` and thus have all the properties of `dcat:Resource`.

**Comment by henrietteharmse** [comment]
Done
