### ISSUE TITLE
Replace `dcterms:keyword` with `dcat:keyword`

### ISSUE THREAD

**Issue by henrietteharmse** [ejp-rd-vp/resource-metadata-schema#70]
Currently `dcat:Resource` has a `dcterms:keyword` property. However, there is no `keyword` property in the `dcterms` namespace. It may be best to replace `dcterms:keyword` with `dcat:keyword`.

**Comment by Daniela-VicentiniAlbring** [comment]
Done

**Comment by brunasv** [comment]
corrected diagram and readme. @markwilkinson corrected shacls
