### ISSUE TITLE
Replace `dcterms:location` with `dcat:contactPoint`

### ISSUE THREAD

**Issue by henrietteharmse** [ejp-rd-vp/resource-metadata-schema#71]
Currently `foaf:Organisation` refers to `dcterms:location`. However, there is no `location` property in the `dcterms` namespace. This may have been confused with the `dcterms:Location` class   

It may be a good idea to replace `dcterms:location` with `dcat:contactPoint` with range `vCard:Agent`, which is already used for `dcat:Resource`.

**Comment by markwilkinson** [comment]
Done... I think  :-)
