### ISSUE TITLE
How to properly fill in the field "Contact Point" from Dataset

### ISSUE THREAD

**Issue by mirgin01** [ejp-rd-vp/resource-metadata-schema#72]
Hi!
I'm currently working to create the FDP for the EGA level 1. 
We've already deployed a regular FDP (not a FiaB) and I've been following these [instructions](https://github.com/ejp-rd-vp/FDP-Reference-Implementation-Configuration). I was able to follow them and create the schemas and links. Once this was done, I created a _Catalog_ with the EGA information and then a _Dataset_ linked to this _Catalog_. However, I encountered an issue that prevents the saving of the _Dataset_ information. 
When I don't fill in the  _Contact point_ section (which is not tagged as mandatory) I get the error of photo1. And, when I fill it with the  EGA contact form URL, it raises ther error in photo2. 
Could you help me with the format this section needs?
Thanks!!
Mireia

![photo2](https://github.com/ejp-rd-vp/resource-metadata-schema/assets/100416435/094575af-6966-4255-b6cc-169e46431828)

![photo1](https://github.com/ejp-rd-vp/resource-metadata-schema/assets/100416435/b05a97ad-034a-45af-a293-ac68c59b7f6c)

@andrawaag
@ericprud
@markwilkinson
@HaddadTala

**Comment by markwilkinson** [comment]
Hi Mireia, 

It appears that you are not using the latest shacl that is in the Configuration instructions github.  Contact Point should not look like that in the web interface - it should have a "URL" sub-property

```
:ContactShape a sh:NodeShape ;  # New section
  sh:targetClass vcard:Agent ;
  sh:property [
    sh:path vcard:url;
    sh:name "URL" ;
    sh:nodeKind sh:IRI ;
    sh:minCount 1 ;
    sh:maxCount  1 ;
    dash:editor dash:URIEditor ;
    dash:viewer dash:LabelViewer ;
  ] .
```

**Comment by markwilkinson** [comment]
I suggest that you edit the Schema for "Dataset" and replace the shacl with this one:  https://github.com/ejp-rd-vp/FDP-Reference-Implementation-Configuration/blob/main/shacl/dataset.shacl

That should get you on your way!

**Comment by mirgin01** [comment]
Thanks for your quick answer, it worked !!
In the [instructions](https://github.com/ejp-rd-vp/FDP-Reference-Implementation-Configuration) I was following the only shacl that needed to be modified were Resource, Data service and Patient registry. 
Maybe it's because they are specific for FiaB and not for FDP.

**Comment by markwilkinson** [comment]
No, it's an error in the documentation.  I forgot that we moved the contact point up into the Resource and removed it from Dataset... so the editing of Dataset is a missing step in the docs. I will fix that right now!  Thanks for noticing!
