### ISSUE TITLE
Distribution and DataServices

### ISSUE THREAD

**Issue by svituz** [ejp-rd-vp/resource-metadata-schema#73]
@markwilkinson and @Orphanet 
in BBMRI we have some Biobanks that implement two endpoints VP Beacon and VP Individuals.
I need to represent these Biobanks in the FDP. Since they are two different endpoints I would like to understand how should they be related to the Distribution: I believe they should be represented as Dataset with one Distribution and two DataService. 
Is it correct? The other option is Dataset with two Distributions each having one DataService.

**Comment by markwilkinson** [comment]
You are correct.  A Distribution with two accessService connections.  Each access service points back (servesDataset) to the Dataset object (not the Distribution!  It's weird... but that's how DCAT has defined it...).  That backwards linkage is important to the VP, so don't forget it!

**Comment by markwilkinson** [comment]
Marked as closed unless you have additional questions
