### ISSUE TITLE
Describing DataService for a Catalog

### ISSUE THREAD

**Issue by svituz** [ejp-rd-vp/resource-metadata-schema#74]
@markwilkinson, @Orphanet
I have a doubt about linking the DataService to its Catalog. 
From the [schema](https://github.com/ejp-rd-vp/resource-metadata-schema/blob/master/images/diagram_onboarding_doc/Class%20Diagram%20-%20EJP%20RD%20MM.png) the Catalog specifies the DataService containing endpoint to query, using the `dcat:service` property and this is how we implemented it in the BBMRI Directory FDP. The Dataset instead uses a `dcat:Distribution` that points to the DataService. Since the Catalog inherits from DataSet it may be misleading. I'm wondering because the current implementation of the portal's SPARQL query doesn't consider the `dcat:Catalog dcat:service dcat:DataService` triple and so the BBMRI Directory is not returned. Do we need to add a Distribution or should the portal consider this case?

**Comment by markwilkinson** [comment]
There are two kinds of data services in EJP - services that provide access to a Dataset, and services that do "pure analytics" (like graphing or statistics).  The former is provided as an accessService to a Distribution.  The latter is a dcat:service from a Catalog.

Hope that helps!
