### ISSUE TITLE
`dcat:version` versus `dct:hasVersion`

### ISSUE THREAD

**Issue by egonw** [ejp-rd-vp/resource-metadata-schema#76]
The `dataservices.shex` shape uses `dct:hasVersion`, but the documentation at https://vp-onboarding-doc.readthedocs.io/en/latest/level_1/properties/data_service.html uses `dcat:version`. Which one should it be?

**Comment by markwilkinson** [comment]
Can you point me to the data services shex that you are referring to?

dcat:version is the correct one.  I'll fix the shex once I am sure I am looking in the right place.

**Comment by markwilkinson** [comment]
(in principle, you shouldn't be looking at ShEx at all, since these are always non-canonical.  We only rely on SHACL for all things FDP)

**Comment by markwilkinson** [comment]
I found the shex and fixed it.  I will discuss this shex/shacl issue with the metadata team

THanks for the report!

**Comment by egonw** [comment]
> I found the shex and fixed it. I will discuss this shex/shacl issue with the metadata team

Sorry, only just now saw the replies. Thanks for updaing the shex! I am using them (tho I have to check which versions) to validate the FDP content before publishing (just for the record; no expectations implied).
