### ISSUE TITLE
`dcat:theme` versus `dct:theme`

### ISSUE THREAD

**Issue by egonw** [ejp-rd-vp/resource-metadata-schema#78]
Another inconsistency, I think. `dcat:theme` is used in various places, so I guess the  `dct:theme` in https://vp-onboarding-doc.readthedocs.io/en/latest/level_1/properties/data_service.html is wrong?

**Comment by markwilkinson** [comment]
That's correct.  I have notified the onboarding team. I'll close this when it is fixed.

**Comment by markwilkinson** [comment]
fixed.  Thanks Egon!
