### ISSUE TITLE
Catalogue location Organization

### ISSUE THREAD

**Issue by markwilkinson** [ejp-rd-vp/resource-metadata-schema#9]
I'm guessing that you're using schema.org for these structures?

My reading of Schema does not allow Organization to be the range of the location predicate (it can be the domain, but not the range)  (See Catalog model)

**Comment by markwilkinson** [comment]
I'm going to use "creator" in my models, until you suggest your preferred predicate

CreativeWork - creator - Organization

**Comment by simonjupp** [comment]
After the meeting this week Catalogs and Datasets use a `dc:publisher` relation to a `foaf:Organisation`. The organisation points to `dc:LocationPeriodOrJurisdiction` using the `dc:spatial` predicate.

**Comment by rajaram5** [comment]
We included location property in metadata model
